# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContact():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contact(self):
    self.driver.get("http://localhost:8004/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Order Now").click()
    self.driver.find_element(By.ID, "username").send_keys("aditya1")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > .col-md-3:nth-child(3) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
    self.driver.find_element(By.ID, "name").send_keys("aditya")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("aditya45@gmail.com")
    self.driver.find_element(By.ID, "mobile").click()
    self.driver.find_element(By.ID, "mobile").send_keys("7007593566")
    self.driver.find_element(By.ID, "subject").click()
    self.driver.find_element(By.ID, "subject").send_keys("food quality")
    self.driver.find_element(By.ID, "message").click()
    self.driver.find_element(By.ID, "message").click()
    self.driver.find_element(By.ID, "message").send_keys("quality was not good")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
    self.driver.find_element(By.ID, "username").send_keys("aditya1")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.LINK_TEXT, "Home").click()
  
